const FATCH = 'FATCH'
const CREATE = 'CREATE'
const UPDATE = 'UPDATE'
const LIKE = 'LIKE'
const DELETE = 'DELETE'
const AUTH = 'AUTH'
const SEARCH = 'SEARCH'
const START_LOADING = 'START_LOADING'
const END_LOADING = 'END_LOADING'
const GET_SINGLE_POST = 'GET_SINGLE_POST'
const SEARCH_BY_TAG = 'SEARCH_BY_TAG'
const COMMENT_ON_POST = 'COMMENT_ON_POST'
const LOGOUT = 'LOGOUT'
export {
  FATCH,
  GET_SINGLE_POST,
  CREATE,
  UPDATE,
  LIKE,
  DELETE,
  COMMENT_ON_POST,
  SEARCH,
  SEARCH_BY_TAG,
  START_LOADING,
  END_LOADING,
  AUTH,
  LOGOUT,
}
